export const WATCH_APP_PACKAGE_NAME = 'WATCH_APP_PACKAGE_NAME'

export const PHONE_APP_FINGERPRINT = 'WATCH_APP_FINGERPRINT'

export const PHONE_APP_PACKAGE_NAME = 'PHONE_APP_PACKAGE_NAME'

export default { WATCH_APP_PACKAGE_NAME, PHONE_APP_FINGERPRINT, PHONE_APP_PACKAGE_NAME }